version: "3"

networks:
  consumer-network:
  kafka-cluster:
    name: kafka-cluster
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:3.6.2
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-cluster

  kafka1:
    image: bitnami/kafka:2.7.0
    container_name: kafka1
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS= "india:1:1,egypt:1:1,singapore:1:1"
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster

  kafka2:
    image: bitnami/kafka:2.7.0
    container_name: kafka2
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS= "india:1:1,egypt:1:1,singapore:1:1"
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster

  kafka3:
    image: bitnami/kafka:2.7.0
    container_name: kafka3
    ports:
      - '9095:9095'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9092,EXTERNAL://localhost:9095
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS= "india:1:1,egypt:1:1,singapore:1:1"
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster

  consumer-1:
    image: consumer.jar
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: consumer-1
    environment:
      - SERVER_PORT = 8080
      - CONSUMER_GROUP = group_1
    ports:
      - "8080:8080"
    networks:
      - kafka-cluster

  consumer-2:
    image: consumer.jar
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: consumer-2
    environment:
      - SERVER_PORT = 8081
      - CONSUMER_GROUP = group_2
    ports:
      - "8081:8081"
    networks:
      - kafka-cluster

  consumer-3:
    image: consumer.jar
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: consumer-3
    environment:
      - SERVER_PORT = 8082
      - CONSUMER_GROUP = group_3
    ports:
      - "8082:8082"
    networks:
      - kafka-cluster

  consumer-4:
    image: consumer.jar
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: consumer-4
    environment:
      - SERVER_PORT = 8083
      - CONSUMER_GROUP = group_4
    ports:
      - "8083:8083"
    networks:
      - kafka-cluster

  consumer-5:
    image: consumer.jar
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: consumer-5
    environment:
      - SERVER_PORT = 8084
      - CONSUMER_GROUP = group_5
    ports:
      - "8084:8084"
    networks:
      - kafka-cluster