#spring:
#  kafka:
#    producer:
#      bootstrap-servers: kafka1:9092, kafka2:9092, kafka3:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer