#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9093, localhost:9094, localhost:9095
#      group-id: group_1
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer